### ISSUE TITLE
Used licensing

### ISSUE THREAD

**Issue by tinohager** [jsauve/AASharp#7]
Would you possibly change the used license  LGPL-3.0 to [MIT_License](https://en.wikipedia.org/wiki/MIT_License)?
It would make it easier to use in other projects.

**Comment by elendil-software** [comment]
I recently participated actively to this repository but it's not mine.
I took the liberty to put a LGPL license on this repository when I built a NuGet Package. I tried to choose one that follow the best the conditions of the original library (AA+).

The LGPL allows you to use AASharp in any kind of software (free, commercial, ...). The only difference I see with the MIT License is that with the LGPL if you modify the library's code you have to disclose these modifications.

Can you explain me why you would need it under MIT license ?

**Comment by tinohager** [comment]
We want use your library in our project but my project is use also in other projects. I know big companys must check the licence terms before she can use third party libraries. I want to make it as easy as possible for them here. I will also change the license of my project to MIT.

My Project: https://github.com/tinohager/Nager.Date

https://softwareengineering.stackexchange.com/questions/81947/why-is-jquery-released-under-mit-and-not-lgpl

**Comment by elendil-software** [comment]
> I know big companys must check the licence terms

And the small companies too... :-)

I still don't understand why do you find it's complicated to include a LGPL library in another software (free or proprietary). 
- If you add AASharp as a dependency (by including the nuget package for example) of your library there is no problem.
- If you take the AASharp source code, build the DLL yourself and put it with your project, there is no problem as long as you disclose any modification done in the AASharp library code.
- But if you want to include the AASharp source code or part of the AASharp there is a problem : you would have to release your own library under the LGPL license.

With the MIT license, if someone want to take the code, modify it (correct bugs, improve it, ...) and include it in their project without giving back the improvements they made, they can. That's the point I would like to avoid : that someone take all the work done by the AASharp contributors, without giving anything back (if they modify the code).

Well, that's how I understand these two licenses. I'm a software engineer, not a lawyer :-)

@jsauve , what do you think ?

**Comment by tinohager** [comment]
If a commercial project use the library and a customer buy a source code licence (for example here https://afterlogic.com/purchase/net-email-components -> Purchase Source Code) he must change the license.

I'm a software engineer too, and complex licensing is a difficult topic that does not make our lives easier.

**Comment by elendil-software** [comment]
> he must change the license.

Change the licence of what ?

If such company use a library under LGPL license they have to :

- tell they use such library (In an About dialog box for example).
- indicate the copyright and license and a way to access to the source code (a link to the GitHub repository or the library website for example). 
- if they modify the source code, they have to provide the source code of the modified library 

The only case where they have to release the source code of their software is if they use the source code of the LGPL library directly in their own source code. In this case they have to disclose their code under LGPL license.

Example of a library under LGPL : 7-zip. I found it in various softwares on my computer. Some are available at no cost, some are paid software : 

- Jetbrains Toolbox
- Atlassian SourceTree
- Beyond Compare 4
- PixInsight 1.8
- Adobe (installed in Common Files)

They don't seems to have problem to include LGPL libraries in their software.

Here is two questions you can find in the 7-Zip developer FAQ (http://www.7-zip.org/faq.html#developer_faq)

_Can I use the EXE or DLL files from 7-Zip in a Commercial Application?_
Yes, but you are required to specify in your documentation (1) that you used parts of the 7-Zip program, (2) that 7-Zip is licensed under the GNU LGPL license and (3) you must give a link to www.7-zip.org, where the source code can be found.

_Can I use the source code of 7-Zip in a commercial application?_
Since 7-Zip is licensed under the GNU LGPL you must follow the rules of that license. In brief, it means that any LGPL'ed code must remain licensed under the LGPL. For instance, you can change the code from 7-Zip or write a wrapper for some code from 7-Zip and compile it into a DLL; but, the source code of that DLL (including your modifications / additions / wrapper) must be licensed under the LGPL or GPL. Any other code in your application can be licensed as you wish. This scheme allows users and developers to change LGPL'ed code and recompile that DLL. That is the idea of free software. Read more here: http://www.gnu.org/. You can also read about the LZMA SDK, which is available under a more liberal license.

**Comment by toddcarnes** [comment]
If the license is causing you problems, you should use a different
solution, not ask to have the license changed for your convenience.

On Mar 8, 2018 08:53, "Tino Hager" <notifications@github.com> wrote:

If a commercial project use the library and a customer buy a source code
licence (for example here https://afterlogic.com/
purchase/net-email-components -> Purchase Source Code) he must change the
license.

I'm a software engineer too, and complex licensing is a difficult topic
that does not make our lives easier.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jsauve/AASharp/issues/7#issuecomment-371548651>, or mute
the thread

**Comment by elendil-software** [comment]
If such company use a library under LGPL license they have to :

- tell they use such library (In an About dialog box for example).
- indicate the with copyright and a way to access to the source code (a link to the GitHub repository for example). 
- if they modify the source code, they have to provide the library's modified source code.

But they can't use the source code of the LGPL library directly in their own source code. In this case they have to disclose their code under LGPL license.


Example of a library under LGPL : 7-zip. I found it in various softwares on my computer. Some are available at no cost, some are paid software : 

- Jetbrains Toolbox
- Atlassian SourceTree
- Beyond Compare 4
- PixInsight 1.8
- Adobe (installed in Common Files)

They don't seems to have problem to include LGPL libraries in their software.

Here is two question you can find in the 7-Zip developer FAQ (http://www.7-zip.org/faq.html#developer_faq)

Can I use the EXE or DLL files from 7-Zip in a Commercial Application?

Yes, but you are required to specify in your documentation (1) that you used parts of the 7-Zip program, (2) that 7-Zip is licensed under the GNU LGPL license and (3) you must give a link to www.7-zip.org, where the source code can be found.

Can I use the source code of 7-Zip in a commercial application?

Since 7-Zip is licensed under the GNU LGPL you must follow the rules of that license. In brief, it means that any LGPL'ed code must remain licensed under the LGPL. For instance, you can change the code from 7-Zip or write a wrapper for some code from 7-Zip and compile it into a DLL; but, the source code of that DLL (including your modifications / additions / wrapper) must be licensed under the LGPL or GPL. Any other code in your application can be licensed as you wish. This scheme allows users and developers to change LGPL'ed code and recompile that DLL. That is the idea of free software. Read more here: http://www.gnu.org/. You can also read about the LZMA SDK, which is available under a more liberal license.

**Comment by elendil-software** [comment]
@toddcarnes Thanks

**Comment by tinohager** [comment]
Thanks for the Feedback.
